# Generated by Django 3.1.5 on 2021-03-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='price',
            field=models.FloatField(),
        ),
    ]
